# Generated by Django 4.1.5 on 2023-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []
