# Generated by Django 4.1.5 on 2023-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_site_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=20)),
                ('name_teacher', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.DurationField()),
            ],
        ),
    ]
